<?php

namespace App\Services\SaturnYaml;

use App\Services\RepositoryAnalyzer\DTOs\AnalysisResult;
use App\Services\RepositoryAnalyzer\DTOs\AppDependency;
use App\Services\RepositoryAnalyzer\DTOs\DetectedApp;
use App\Services\RepositoryAnalyzer\DTOs\DetectedDatabase;
use Symfony\Component\Yaml\Yaml;

/**
 * Generates saturn.yaml content from a repository analysis result.
 */
class SaturnYamlGenerator
{
    /**
     * Generate saturn.yaml content from an analysis result.
     */
    public function generate(AnalysisResult $result, string $gitBranch = 'main'): string
    {
        $config = ['version' => '1'];

        // Build depends_on map: app name → list of dependency names
        $dependsOnMap = $this->buildDependsOnMap($result);

        // Applications section
        $applications = $this->buildApplicationsSection($result, $gitBranch, $dependsOnMap);
        if (! empty($applications)) {
            $config['applications'] = $applications;
        }

        // Databases section
        $databases = $this->buildDatabasesSection($result->databases);
        if (! empty($databases)) {
            $config['databases'] = $databases;
        }

        // Shared variables section (env vars without a default value are excluded)
        $sharedVars = $this->buildSharedVariablesSection($result);
        if (! empty($sharedVars)) {
            $config['shared_variables'] = $sharedVars;
        }

        $header = implode("\n", [
            '# saturn.yaml — auto-generated by Saturn Platform',
            '# Documentation: https://docs.saturn.ac/saturn-yaml',
            '# Edit freely: Saturn will sync on next deploy.',
            '',
        ]);

        return $header.Yaml::dump($config, 6, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
    }

    /**
     * Build applications section of the config.
     *
     * @param  array<string, string[]>  $dependsOnMap
     * @return array<string, mixed>
     */
    private function buildApplicationsSection(AnalysisResult $result, string $gitBranch, array $dependsOnMap): array
    {
        $applications = [];

        foreach ($result->applications as $app) {
            $appConfig = $this->buildSingleApplication($app, $gitBranch, $result);

            // Inject depends_on (db names + app names from app dependency graph)
            $deps = $dependsOnMap[$app->name] ?? [];
            if (! empty($deps)) {
                $appConfig['depends_on'] = $deps;
            }

            // Inject environment variables pointing to detected databases
            $envSection = $this->buildEnvSection($app->name, $result);
            if (! empty($envSection)) {
                $appConfig['environment'] = $envSection;
            }

            $applications[$app->name] = $appConfig;
        }

        return $applications;
    }

    /**
     * Build config for a single detected application.
     *
     * @return array<string, mixed>
     */
    private function buildSingleApplication(DetectedApp $app, string $gitBranch, AnalysisResult $result): array
    {
        $config = [];

        $config['build'] = $app->buildPack;

        if ($gitBranch !== 'main') {
            $config['git_branch'] = $gitBranch;
        }

        // base_directory only if not root
        if ($app->path !== '.' && $app->path !== '') {
            $config['base_directory'] = '/'.$app->path;
        }

        if ($app->publishDirectory) {
            $config['publish_directory'] = $app->publishDirectory;
        }

        if ($app->installCommand) {
            $config['install_command'] = $app->installCommand;
        }

        if ($app->buildCommand) {
            $config['build_command'] = $app->buildCommand;
        }

        if ($app->startCommand) {
            $config['start_command'] = $app->startCommand;
        }

        if ($app->buildPack === 'dockerfile' && $app->dockerfileLocation) {
            $config['dockerfile_location'] = $app->dockerfileLocation;
        }

        $config['application_type'] = $app->applicationMode;

        if ($app->defaultPort > 0 && $app->applicationMode !== 'worker') {
            $config['ports'] = $app->defaultPort;
        }

        if ($app->healthCheck) {
            $config['healthcheck'] = [
                'path' => $app->healthCheck->path,
                'interval' => $app->healthCheck->intervalSeconds,
                'timeout' => $app->healthCheck->timeoutSeconds,
            ];
        }

        return $config;
    }

    /**
     * Build databases section.
     *
     * @param  DetectedDatabase[]  $databases
     * @return array<string, mixed>
     */
    private function buildDatabasesSection(array $databases): array
    {
        $section = [];

        foreach ($databases as $db) {
            $dbConfig = ['type' => $db->type];

            $section[$db->name] = $dbConfig;
        }

        return $section;
    }

    /**
     * Build environment section for a specific app, using @ref syntax for DB connections.
     *
     * @return array<string, string>
     */
    private function buildEnvSection(string $appName, AnalysisResult $result): array
    {
        $env = [];

        // Map DB type → env var name → @ref
        foreach ($result->databases as $db) {
            if (in_array($appName, $db->consumers, true)) {
                $env[$db->envVarName] = "@{$db->name}.connection_string";
            }
        }

        // Add non-sensitive env vars from detected env variables for this app
        foreach ($result->envVariables as $envVar) {
            if ($envVar->forApp !== $appName) {
                continue;
            }
            // Skip db connection vars (already covered above)
            if (isset($env[$envVar->key])) {
                continue;
            }
            // Only include vars with a concrete default (skip placeholders)
            if (! empty($envVar->defaultValue) && ! $this->looksLikeSecret($envVar->key)) {
                $env[$envVar->key] = $envVar->defaultValue;
            }
        }

        return $env;
    }

    /**
     * Build shared_variables section from environment-level vars.
     *
     * @return array<string, string>
     */
    private function buildSharedVariablesSection(AnalysisResult $result): array
    {
        $shared = [];

        // Collect env vars that appear in multiple apps (truly shared)
        $keyCount = [];
        foreach ($result->envVariables as $env) {
            $keyCount[$env->key] = ($keyCount[$env->key] ?? 0) + 1;
        }

        foreach ($result->envVariables as $env) {
            if (($keyCount[$env->key] ?? 0) < 2) {
                continue;
            }
            if (empty($env->defaultValue) || $this->looksLikeSecret($env->key)) {
                continue;
            }
            $shared[$env->key] = $env->defaultValue;
        }

        return $shared;
    }

    /**
     * Build depends_on map: app name → [db names + app dependency names].
     *
     * @return array<string, string[]>
     */
    private function buildDependsOnMap(AnalysisResult $result): array
    {
        $map = [];

        // DB consumers → depends on that DB
        foreach ($result->databases as $db) {
            foreach ($db->consumers as $consumer) {
                $map[$consumer][] = $db->name;
            }
        }

        // App-to-app dependencies from dependency analyzer
        /** @var AppDependency $dep */
        foreach ($result->appDependencies as $dep) {
            foreach ($dep->dependsOn as $depName) {
                $map[$dep->appName][] = $depName;
            }
        }

        // Deduplicate
        foreach ($map as $name => $deps) {
            $map[$name] = array_values(array_unique($deps));
        }

        return $map;
    }

    /**
     * Heuristic: skip secrets / tokens / passwords in generated yaml.
     */
    private function looksLikeSecret(string $key): bool
    {
        $patterns = ['SECRET', 'PASSWORD', 'PASS', 'TOKEN', 'KEY', 'PRIVATE', 'CREDENTIAL', 'AUTH'];
        $upper = strtoupper($key);
        foreach ($patterns as $pattern) {
            if (str_contains($upper, $pattern)) {
                return true;
            }
        }

        return false;
    }
}
